### ISSUE TITLE
sync problem

### ISSUE THREAD

**Issue by jaime25680** [zoldur/JIYO#1]
hi zoldur i am having an issue trying to sync the blocks when i use jiyo-cli mnsync status to check the block it stay at 3659, all i do is start with the install command then after jiyo is installed i try and check blocks and thats what happens. thank you

**Comment by zoldur** [comment]
Sometimes the chain get stuck and my suggestion is to resync it. Try this:
```
systemctl stop Jiyo
rm -r /root/.jiyo/{backups,blocks,budget.dat,chainstate,database,db.log,debug.log,fee_estimates.dat,jiyod.pid,masternode.conf,mncache.dat,mnpayments.dat,peers.dat,sporks,zerocoin}
systemctl start Jiyo
```
